# Generated by Django 5.2.4 on 2025-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=99)),
                ('priority', models.CharField(choices=[('IMPORTANT', 'IMPORTANT'), ('ANNOUNCEMENT', 'ANNOUNCEMENT'), ('NEWS', 'NEWS')], default='IMPORTANT', max_length=20)),
                ('priority_colors', models.CharField(choices=[('red', 'Red'), ('rreen', 'Green'), ('blue', 'Blue')], default='red', max_length=20)),
                ('live', models.IntegerField(choices=[(1, 'Live'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'order'],
            },
        ),
    ]
