# Generated by Django 5.2.4 on 2025-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='latestupdates',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='latestupdates',
            name='priority',
            field=models.CharField(choices=[('IMPORTANT', 'IMPORTANT'), ('ANNOUNCEMENT', 'ANNOUNCEMENT'), ('NEWS', 'NEWS'), ('KEYNOTE SPEAKER', 'KEYNOTE SPEAKER')], default='IMPORTANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='latestupdates',
            name='priority_colors',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('teal', 'Teal'), ('brown', 'Brown'), ('gray', 'Gray'), ('black', 'Black'), ('white', 'White')], default='red', max_length=20),
        ),
    ]
