# Generated by Django 5.2.4 on 2025-08-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_latestupdates_options_and_more'),
        ('common', '0003_page_alter_latestupdates_options_and_more'),
    ]

    operations = [
    ]
