# Generated by Django 5.2.4 on 2025-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_page_alter_latestupdates_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prev_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField()),
                ('is_firm_deadline', models.BooleanField(default=False)),
            ],
        ),
    ]
