# Generated by Django 5.2.4 on 2025-08-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_conferenceevent'),
        ('common', '0004_merge_20250817_0102'),
    ]

    operations = [
    ]
