# Generated by Django 5.2.4 on 2025-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
