# Generated by Django 5.2.4 on 2025-09-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_hotel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='remark',
        ),
        migrations.AddField(
            model_name='hotel',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
    ]
