# Generated by Django 5.2.4 on 2025-09-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_0004_conferenceevent_0004_merge_20250817_0102'),
        ('common', '0007_remove_hotel_remark_hotel_breakfast'),
    ]

    operations = [
    ]
