# Generated by Django 5.2.4 on 2025-10-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_hotel_remark_hotel_breakfast'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=100)),
                ('button_colors', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('teal', 'Teal'), ('brown', 'Brown'), ('gray', 'Gray'), ('black', 'Black'), ('white', 'White')], max_length=20)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=99)),
                ('is_live', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='quick_links_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Page_Name', to='common.page')),
            ],
        ),
    ]
