# Generated by Django 5.2.4 on 2025-10-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_merge_20250907_0058'),
        ('common', '0008_quicklink'),
    ]

    operations = [
    ]
