# Generated by Django 5.2.4 on 2025-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_merge_0008_merge_20250907_0058_0008_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='target',
            field=models.CharField(choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
    ]
