# Generated by Django 5.2.4 on 2025-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_quicklink_icon_svg_quicklink_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='text_color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('teal', 'Teal'), ('brown', 'Brown'), ('gray', 'Gray'), ('black', 'Black'), ('white', 'White')], default='white', max_length=20),
        ),
    ]
