# Generated by Django 5.2.4 on 2025-07-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
