# Generated by Django 4.2.23 on 2025-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_alter_committeemember_profile_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['committee', 'order']},
        ),
        migrations.AddField(
            model_name='committeemember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
