# Generated by Django 4.2.23 on 2025-07-10 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0004_committeemember_added_by_committeemember_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='bio',
        ),
        migrations.AddField(
            model_name='speaker',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speaker',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='bio_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='bio_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
