# Generated by Django 4.2.23 on 2025-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_alter_speaker_options_remove_speaker_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='object_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='object_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='speaker',
            name='object_status',
            field=models.IntegerField(default=1),
        ),
    ]
