# Generated by Django 4.2.23 on 2025-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_committee_object_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image_path',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
    ]
