# Generated by Django 5.2.4 on 2025-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_alter_speaker_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='link',
            new_name='profile_link',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image_path',
            field=models.ImageField(upload_to='speakers/'),
        ),
    ]
