# Generated by Django 5.2.4 on 2025-07-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_tier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/')),
                ('cost_inr', models.CharField(blank=True, max_length=20, null=True)),
                ('exhibition_space', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_recognition', models.TextField(blank=True, null=True)),
                ('promotional_coverage', models.TextField(blank=True, null=True)),
                ('presentation_time', models.CharField(blank=True, max_length=10, null=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsorship.tier')),
            ],
        ),
    ]
