# Generated by Django 5.2.4 on 2025-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsordetail',
            name='cost_inr',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='exhibition_space',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='presentation_time',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='promotional_coverage',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='stage_recognition',
        ),
        migrations.AddField(
            model_name='tier',
            name='cost_inr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='exhibition_space',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='presentation_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='promotional_coverage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='stage_recognition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
