# Generated by Django 5.2.4 on 2025-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_remove_sponsordetail_cost_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsordetail',
            name='position',
            field=models.IntegerField(choices=[(0, 'Top'), (1, 'Sidebar')], default=1),
        ),
    ]
