# Generated by Django 5.2.4 on 2025-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_sponsordetail_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsordetail',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
