# Generated by Django 5.2.4 on 2025-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_sponsordetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='tier_order',
            field=models.IntegerField(default=0),
        ),
    ]
