# Generated by Django 5.2.4 on 2025-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_tier_tier_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsordetail',
            name='hieght',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsordetail',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
